name: AdminTools
version: '1.0.0'
main: me.GodReorx.adminTools.AdminTools
description: Este plugin es un conjunto de herramientas para admins
api-version: '1.21'
authors: [ GodReorx ]

commands:
  atpunish:
    description: "Comando para lanzar un rayo divino y castigar a los jugadores"
    usage: /atpunish <Player>
    permission: admintools
    permission-message: No tienes permiso para usarlo!
  attpalltome:
    description: "Comando para teleportar a todos los jugadores online al admin"
    usage: /attpalltome
    permission: admintools
    permission-message: No tienes permiso para usarlo!
  attptome:
    description: "Comando para teleportar a un jugador al admin"
    usage: /attptome <Player>
    permission: admintools
    permission-message: No tienes permiso para usarlo!
  attpto:
    description: "Comando para teleportar al admin a un jugador"
    usage: /attpto <Player>
    permission: admintools
    permission-message: No tienes permiso para usarlo!
  atgamemode:
    description: "Comando para modificar el modo de juego a un jugador o todos"
    usage: /atgamemode <Player|All> <Creative|Survival|Adventure|Spectator>
    permission: admintools
    permission-message: No tienes permiso para usarlo!
  atinventoryclean:
    description: "Comando para vaciar el inventario de un jugador o todos"
    usage: /atinventoryclean <Player|All>
    permission: admintools
    permission-message: No tienes permiso para usarlo!

permissions:
  admintools:
    description: Permite el uso de los comandos del AdminTools
    default: op