name: AdminTools
version: '1.0.7'
main: me.GodReorx.adminTools.AdminTools
description: Este plugin es un conjunto de herramientas para admins
api-version: '1.21'
authors: [ GodReorx ]

commands:
  atpunish:
    description: "Smites a player with a divine bolt of lightning."
    usage: /atpunish <Player>
    permission: admintools
    permission-message: You do not have permission to use it!
  attpalltome:
    description: "Teleport all online players to the admin."
    usage: /attpalltome
    permission: admintools
    permission-message: You do not have permission to use it!
  attptome:
    description: "Teleport a specified player to the admin."
    usage: /attptome <Player>
    permission: admintools
    permission-message: You do not have permission to use it!
  attpto:
    description: "Teleport the admin to a specified player."
    usage: /attpto <Player>
    permission: admintools
    permission-message: You do not have permission to use it!
  atgamemode:
    description: "Changes the game mode of a player or all players."
    usage: /atgamemode <Player | All> <Creative | Survival | Adventure | Spectator>
    permission: admintools
    permission-message: You do not have permission to use it!
  atinventoryclean:
    description: "Empties the inventory of a player or all players."
    usage: /atinventoryclean <Player | All>
    permission: admintools
    permission-message: You do not have permission to use it!
  atvanish:
    description: "Toggles the admin's visibility to other players."
    usage: /atvanish
    permission: admintools
    permission-message: You do not have permission to use it!
  atsaveplayer:
    description: "Save player's name, UUID, location, inventory, and experience in a JSON format"
    usage: /atsaveplayer <Player>
    permission: admintools
    permission-message: You do not have permission to use it!
  atloadplayer:
    description: "Load location, inventory, and experience from JSON format"
    usage: /atloadplayer <Player>
    permission: admintools
    permission-message: You do not have permission to use it!
  atadminmode:
    description: "Change to adminMode (creative, clean inventory and save information) and return to playerMode (restore all data)"
    usage: /atadminmode
    permission: admintools
    permission-message: You do not have permission to use it!

permissions:
  admintools:
    description: Allow the use of AdminTools commands.
    default: op